---
title: "p8105_hw5_kx2173"
author: "Ke Xu"
date: "11/19/2021"
output: github_document
---

```{r}
library(tidyverse)
library(stringr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1
```{r}
homicide_df =
  read.csv("./data_oh/homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolved = case_when(
           disposition =="Closed without arrest" ~ "unsolved",
           disposition =="Open/No arrest" ~"unsolved",
           disposition =="Closed by arrest" ~ "solved"
         )) %>% 
  relocate(city_state)%>%
  filter(city_state != "TulsaAL")
```

Let's focus on Baltimore, MD.
```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolved == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>% 
  broom::tidy()
```

Iterate across cities
```{r}
prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>%
    summarize(
      unsolved = sum(resolved == "unsolved"),
      n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
      )
  
  return(city_test)
  
}

prop_test_function(baltimore_df)
```

```{r}
homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```

```{r}
results_df = 
  homicide_df %>% 
  nest(data = uid:resolved) %>% 
  mutate(
    test_results = map(data,prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

Another way of iteration
```{r}
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolved == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

Make a plot
```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


## Problem 2
```{r}

# Read and tidy data
file_name_df = list.files(path = "./data", ignore.case = TRUE)

study_header_name = file_name_df %>% 
  as.data.frame() %>% 
  rename(participate_id = 1)

file_base = "./data/"
vec_file =str_c(file_base, file_name_df)

study_df = map_df(vec_file, read.csv) %>% 
  cbind(study_header_name) %>% 
  mutate(participate_id = str_sub(participate_id, end = 6)) %>% 
  separate(col = participate_id, into = c("group", "id")) %>% 
  pivot_longer(week_1:week_8,
               values_to = "score",
               names_to = "week"
  ) %>%
  mutate(group = case_when(group == "con" ~ "Control",
                         group == "exp" ~ "Experiment"))


# Make a spaghetti plot
study_plot = study_df %>% 
  ggplot(aes(x = week, y = score, color = group,
             group = interaction(group, id))) +
  geom_line() +
  labs(title = "Observed data for each subject over two months",
       x = "Week",
       y = "Score") +
  scale_x_discrete(labels = c(
    "Week 1",
    "Week 2",
    "Week 3",
    "Week 4",
    "Week 5",
    "Week 6",
    "Week 7",
    "Week 8"
  )) +
  scale_color_discrete("Group") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.5))
```
#### Differences between groups:
Based on the plot we got, we can find that the mean value of the experiment arm group is greater than the mean value of the control arm group. The trend of the control arm group is flatter than that of the experiment arm group.


## Problem 3
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

fill_missing_value = function(x){
  if(is.numeric(x)){
    x = replace(x, is.na(x), mean(x, na.rm = TRUE))
  }
  else if(is.character(x)){
    x = replace(x, is.na(x), "virginica")
  }
  
  return(x)
}

iris_filled = map_df(.x = iris_with_missing, ~ fill_missing_value(.x)) %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  view()
```












